#This should later be in a loop around StudyIDs
StudyID=CFTY720D2201E2

ImgType=$1 # Here we only use T13D and T12D

RunID=1

set -e

Mem=8G
Time="20:00:00"

DirSuffix="ANTs2MNI"

NVROXSOURCEDIR=/home/bdivdi.local/dfgtyk/NVROXBOX/SOURCE

# This will be changed later
AllDataDir="/data/output/habib"

PathProcParent=${AllDataDir}/processed/${StudyID}
PathUnProcParent=${AllDataDir}/unprocessed/${StudyID} 

# These info should be already available via getinfo scripts
MetaStudyDataDir="${HOME}/NVROXBOX/Data/${StudyID}"

# Text file which contains the Subjects full directory -- generated by getinfo
StudySubIDFile="${MetaStudyDataDir}/SubDirID_${StudyID}.txt"

#Submitter files, just save the path to them for future mass re-producing
SubmitterPath="${MetaStudyDataDir}/SLUMR_${DirSuffix}_Submitters_${StudyID}_${ImgType}.txt"
rm -f ${SubmitterPath}

while read SubID
do
	# Get the SubID from the directory path
        SubID=`basename $SubID`
	echo "For Subject: $SubID ========================================"

	MetaSubDataDir=${MetaStudyDataDir}/${SubID}
        mkdir -p ${MetaSubDataDir}

	# Conatins the directory to sessions/visits for each subject
	SessionFileName="${MetaStudyDataDir}/Sessions/${StudyID}_${SubID}_Sessions.txt"

	echo "=== Available sessions:"
        cat ${SessionFileName}

	while read Ses
	do

		Ses=`basename $Ses`
        	#Image Name
        	if [ $ImgType == T13D ] ; then
                	#sub-2okKlAKGz7_ses-V1_M2_acq-3d_run-1_T1w.nii.gz
			ImageName=${SubID}_${Ses}_acq-3d_run-${RunID}_T1w
		elif [ $ImgType == T12D ] ; then
                	#sub-2okKlAKGz7_ses-V1_M2_run-1_T1w.nii.gz
                	ImageName=${SubID}_${Ses}_run-${RunID}_T1w
        	elif [ $ImgType == PD2D ] ; then
                        #sub-2okKlAKGz7_ses-V1_M2_run-1_PDT2_1.nii.gz
                        ImageName=${SubID}_${Ses}_run-${RunID}_PDT2_1
                elif [ $ImgType == T22D ] ; then
                        #sub-2okKlAKGz7_ses-V1_M2_run-1_PDT2_2.nii.gz
                        ImageName=${SubID}_${Ses}_run-${RunID}_PDT2_2
                else
                    	# throw an error and halt here
                        echo "$ImgType is unrecognised"
        	fi

		# Reconstruct the directory name
		OutputDir=${PathProcParent}/${SubID}/${Ses}/anat/${ImageName}.ANTs 
#===================================================================		
    		# Check whether the file actually exists
    		if [ ! -d $OutputDir ];
    		then
    			echo "*** Does Not Exist: ${OutputDir} ";
			continue
      		fi
#===================================================================

		OutputDir=${PathProcParent}/${SubID}/${Ses}/anat/${ImageName}.ANTs

		MNIDir=${OutputDir}/MNI

		MetaOpDataDir=${MetaSubDataDir}/${Ses}/anat/ANTs/${DirSuffix}
		mkdir -p ${MetaOpDataDir}

		JobName=${StudyID}_${ImageName}_${DirSuffix}
       		SubmitterFileName="${MetaOpDataDir}/SubmitMe_${JobName}.sh"
       		echo "${SubmitterFileName}" >> $SubmitterPath

cat > $SubmitterFileName << EOF
#!/bin/bash
#SBATCH --partition=main
#SBATCH --job-name=${JobName}
#SBATCH --mem=${Mem}
#SBATCH --time=${Time}
#SBATCH --output=${MetaOpDataDir}/${JobName}.out
#SBATCH --error=${MetaOpDataDir}/${JobName}.err

# Make the output directory. Keep this line here so you can easily test without making a mess
mkdir -p ${MNIDir} 
### ### ### ### ### ###

# Load packages and software here
ml ANTs

# And now the operations

${NVROXSOURCEDIR}/NVROX-ANTs-CorticalThickness-to-MNI.sh ${OutputDir} ${MNIDir}

### ### ### ### ### ###

EOF
		done<${SessionFileName}

done<${StudySubIDFile}

