function IDP = NVROX_readIDtables_SIENA(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   IDPCFTY720D2201E2T13DSIENAFINALPBVC = IMPORTFILE(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   IDPCFTY720D2201E2T13DSIENAFINALPBVC = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   IDPCFTY720D2201E2T13DSIENAFINALPBVC = importfile('IDP_CFTY720D2201E2_T13D_SIENA_FINALPBVC.txt', 1, 19);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/06/27 17:29:43

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%s)
%	column2: categorical (%C)
%   column3: categorical (%C)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%C%C%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
IDP = table(dataArray{1:end-1}, 'VariableNames', {'SubID','SesID','StudyID','Var1'});
