#!/bin/sh
#
set -e

FIRST_dir=$1
VOLTXTFILE=$FIRST_dir/FIRST-SUBCORTVOL.txt

rm -f $VOLTXTFILE

echo $FIRST_dir

#numVars="15"

${FSLDIR}/bin/fslstats ${FIRST_dir}/T1_first_all_fast_firstseg -H 58 0.5 58.5 \
| sed 's/\.000000//g' | awk 'BEGIN { ORS = " " } { print }'\
| awk '{print $10 " " $49 " " $11 " " $50 " " $12 " " $51 " " $13 " " $52 " " $17 " " $53 " " $18 " " $54 " " $26 " " $58 " " $16 }' >> $VOLTXTFILE


