#!/bin/bash 
#
# Script name: bb_IDP_T1_GM_parcellation
#
# Description: Script to generate the IDPs related to Grey Matter parcellation.
#

#origDir=`pwd`
#scriptName=`basename "$0"`

FSLANAT_dir=$1
Atlas_dir=$2
GMP_dir=$3

GMPTXTFILENAME=$GMP_dir/NVROX-GMPVOLS.txt

mkdir -p ${GMP_dir}

# MNI_to_T1_nonlin_field.nii.gz is equivalent of T1_to_MNI_warp_coef_inv? check the BIANCA website... and Field's code in BIANCA:
#${FSLDIR}/bin/applywarp -i ${Atlas_dir}/GMatlas -o ${GMP_dir}/GMatlas_to_T1 -r ${FSLANAT_dir}/T1/T1 -w ${FSLANAT_dir}/T1_to_MNI_warp_coef_inv.nii.gz --interp=nn

${FSLDIR}/bin/applywarp -i ${Atlas_dir}/GMatlas -o ${GMP_dir}/GMatlas_to_T1 -r ${FSLANAT_dir}/T1 -w ${FSLANAT_dir}/MNI_to_T1_nonlin_field.nii.gz --interp=nn
${FSLDIR}/bin/fslstats -K ${GMP_dir}/GMatlas_to_T1.nii.gz ${FSLANAT_dir}/T1_fast_pve_1.nii.gz -m -v | xargs -n 3 | awk '{print "("$1"*"$2")"}' | bc >> $GMPTXTFILENAME
